modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="restaurantcraft"
version="1.0.0"
displayName="RestaurantCraft"
displayURL="https://modrinth.com/project/restaurantcraft"
credits="Kingslav_Games for the McDonalds schematic"
authors="bwrayne"
description="A Minecraft mod for adding restaurants to the game."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.restaurantcraft]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.restaurantcraft]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration